// Lista de domínios rastreadores conhecidos (baseada em EasyPrivacy / Disconnect.me)
const KNOWN_TRACKERS = new Set([
  // Google Tracking & Ads
  "google-analytics.com",
  "googletagmanager.com",
  "googletagservices.com",
  "doubleclick.net",
  "googlesyndication.com",
  "googleadservices.com",
  "pagead2.googlesyndication.com",
  "adservice.google.com",
  "stats.g.doubleclick.net",
  "ssl.google-analytics.com",
  "www.google-analytics.com",
  "analytics.google.com",

  // Facebook / Meta
  "connect.facebook.net",
  "facebook.net",
  "fbcdn.net",
  "pixel.facebook.com",

  // Analytics
  "hotjar.com",
  "static.hotjar.com",
  "script.hotjar.com",
  "vars.hotjar.com",
  "mixpanel.com",
  "cdn.mxpnl.com",
  "api.mixpanel.com",
  "segment.com",
  "cdn.segment.com",
  "api.segment.io",
  "amplitude.com",
  "api.amplitude.com",
  "cdn.amplitude.com",
  "heap.io",
  "cdn.heapanalytics.com",
  "heapanalytics.com",
  "fullstory.com",
  "rs.fullstory.com",
  "mouseflow.com",
  "cdn.mouseflow.com",
  "crazyegg.com",
  "script.crazyegg.com",
  "chartbeat.com",
  "static.chartbeat.com",
  "ping.chartbeat.net",
  "newrelic.com",
  "js-agent.newrelic.com",
  "bam.nr-data.net",
  "nr-data.net",
  "loggly.com",
  "clarity.ms",
  "c.clarity.ms",
  "clarity.microsoft.com",

  // Ad Networks
  "adnxs.com",
  "ib.adnxs.com",
  "rubiconproject.com",
  "fastlane.rubiconproject.com",
  "openx.net",
  "us-u.openx.net",
  "pubmatic.com",
  "ads.pubmatic.com",
  "casalemedia.com",
  "cm.g.doubleclick.net",
  "adroll.com",
  "d.adroll.com",
  "criteo.com",
  "rtax.criteo.com",
  "static.criteo.net",
  "taboola.com",
  "trc.taboola.com",
  "outbrain.com",
  "amplify.outbrain.com",
  "sharethrough.com",
  "mediago.io",
  "advertising.com",
  "atdmt.com",
  "adbrite.com",
  "adserver.com",
  "trafficjunky.net",
  "moatads.com",

  // Score/Measurement
  "scorecardresearch.com",
  "b.scorecardresearch.com",
  "comscore.com",
  "quantserve.com",
  "pixel.quantserve.com",
  "mediavine.com",

  // Social Buttons (rastreadores)
  "platform.twitter.com",
  "syndication.twitter.com",
  "widgets.pinterest.com",
  "assets.pinterest.com",
  "platform.linkedin.com",
  "snap.licdn.com",
  "s.pinimg.com",
  "ads.linkedin.com",

  // Outros rastreadores comuns
  "amazon-adsystem.com",
  "assoc-amazon.com",
  "images-amazon.com",
  "adsafeprotected.com",
  "adsafe.net",
  "onetrust.com",
  "cookielaw.org",
  "trustarc.com",
  "trustarc.mgr.consensu.org",
  "cdn.consensu.org",
  "iabconsent.com",
  "2mdn.net",
  "bluekai.com",
  "demdex.net",
  "everesttech.net",
  "krxd.net",
  "exelator.com",
  "turn.com",
  "yield.manager",
  "yieldmanager.com",
  "adsrvr.org",
  "tradedesk.com",
  "thetradedesk.com",
  "dmtry.com",
  "mathtag.com",
  "bidswitch.net",
  "nexage.com",
  "lijit.com",
  "tribalfusion.com",
  "kontera.com",
  "intellitxt.com",
  "viglink.com",

  // Fingerprinting
  "maxmind.com",
  "ipqualityscore.com",
  "fingerprintjs.com",
  "cdn.jsdelivr.net",
  "fpjscdn.net",

  // Heatmaps / Session Recording
  "luckyorange.com",
  "lpsnmedia.net",
  "smartlook.com",
  "smartlook.cloud",
  "inspectlet.com",
  "clicktale.net",
  "sessioncam.com",
  "glassbox.com",
  "quantum-metric.com"
]);

// Categorias de rastreadores para exibição
const TRACKER_CATEGORIES = {
  "google-analytics.com": "Analytics",
  "googletagmanager.com": "Tag Manager",
  "doubleclick.net": "Publicidade",
  "googlesyndication.com": "Publicidade",
  "connect.facebook.net": "Social/Rastreamento",
  "hotjar.com": "Heatmap/Sessão",
  "mixpanel.com": "Analytics",
  "segment.com": "Analytics",
  "amplitude.com": "Analytics",
  "heap.io": "Analytics",
  "fullstory.com": "Gravação de Sessão",
  "mouseflow.com": "Heatmap",
  "criteo.com": "Retargeting",
  "taboola.com": "Publicidade",
  "outbrain.com": "Publicidade",
  "scorecardresearch.com": "Medição",
  "comscore.com": "Medição",
  "chartbeat.com": "Analytics",
  "clarity.ms": "Analytics Microsoft",
  "adnxs.com": "Ad Exchange",
  "rubiconproject.com": "Ad Exchange"
};

function getTrackerCategory(hostname) {
  for (const [domain, category] of Object.entries(TRACKER_CATEGORIES)) {
    if (hostname === domain || hostname.endsWith("." + domain)) {
      return category;
    }
  }
  return "Rastreador";
}
